### ISSUE TITLE
Crash Pokecube and Coherent Villages Bug

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheExceptionist/Coherent-Villages#22]
https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues/9

**Comment by Thutmose** [comment]
This probably isn't anything on this end, it is something going wrong on pokecube's end

**Comment by TheExceptionist** [comment]
Most, likely.... Nothing I can do at a moment's glance too. I'll keep my ear to the ground on this one, but some other things take priority over this

**Comment by Thutmose** [comment]
If when I look into fixing it, and I can't get it fixed on my end, then the bug might be due to this being registered for EntityVillageAlchemist instead of AbstractVillageAlchemist, but I will need to do further testing on my end to confirm this.

https://github.com/TheExceptionist/Coherent-Villages/blob/master/src/main/java/net/theexceptionist/coherentvillages/entity/alchemist/AbstractVillagerAlchemist.java#L40

**Comment by TheExceptionist** [comment]
Ahh? Sorry I've been rushing to get updates out the past couple of weeks
My bad
Sorry if my code is messy (The alignment is horrible lol)

**Comment by TheExceptionist** [comment]
Fixed in the next version coming out tomorrow
Notify me if this still persists

**Comment by P3rf3ctXZer0** [comment]
k

**Comment by Thutmose** [comment]
If it does persist after making that change, then it is something needed on my end, I might have time this weekend to look into it

**Comment by TheExceptionist** [comment]
@P3rf3ctXZer0 Still a problem?

**Comment by P3rf3ctXZer0** [comment]
No.
